CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512),
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(200),
  requestor_id BIGINT  REFERENCES users(id),
  CONSTRAINT pk_request PRIMARY KEY (id)
--  CONSTRAINT fk_tags_to_users FOREIGN KEY(requestor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  owner BIGINT NOT NULL REFERENCES users(id),
  name VARCHAR(20) NOT NULL,
  description VARCHAR(200),
  available BOOLEAN NOT NULL,
  request BIGINT REFERENCES requests(id),
  CONSTRAINT pk_item PRIMARY KEY (id)
--  CONSTRAINT fk_tags_to_owner FOREIGN KEY(owner) REFERENCES users(id),
--  CONSTRAINT fk_tags_to_request FOREIGN KEY(request) REFERENCES requests(id)
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id BIGINT REFERENCES items(id),
  booker_id BIGINT REFERENCES users(id),
  status VARCHAR,
  CONSTRAINT pk_bookings PRIMARY KEY (id)
--  CONSTRAINT fk_tags_to_booker_id FOREIGN KEY(booker_id) REFERENCES users(id),
--  CONSTRAINT fk_tags_to_items FOREIGN KEY(item_id) REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(200),
  item_id BIGINT REFERENCES items(id),
  author_id BIGINT REFERENCES users(id),
  CONSTRAINT pk_comments PRIMARY KEY (id)
--  CONSTRAINT fk_tags_to_item_id FOREIGN KEY(item_id) REFERENCES items(id),
--  CONSTRAINT fk_tags_to_author_id FOREIGN KEY(author_id) REFERENCES users(id)
);

